### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by jahfer** [Shopify/rotoscope#55]
We're currently on v0.3.0.pre.4 (soon to be pre.5 probably), but the changes in v0.3.0 have been largely stable for a while. Should cut a proper release once #54 goes in.

**Comment by exterm** [comment]
have bumped the version and pushed the tag, but master is broken because of style guide changes. As this code was previously valid, and hasn't changed, I'd like to push to rubygems as is. Any opinions @jahfer ? Style fix is also available in https://github.com/Shopify/rotoscope/pull/73

**Comment by exterm** [comment]
release is done.
